---
language: python
services: docker

env:
  global:
    - ROLE_NAME: java
  matrix:
    - MOLECULE_DISTRO: geerlingguy/docker-centos8-ansible:latest
    - MOLECULE_DISTRO: geerlingguy/docker-centos7-ansible:latest
    - MOLECULE_DISTRO: geerlingguy/docker-centos6-ansible:latest
    - MOLECULE_DISTRO: geerlingguy/docker-fedora31-ansible:latest
    - MOLECULE_DISTRO: geerlingguy/docker-ubuntu2004-ansible:latest
    - MOLECULE_DISTRO: geerlingguy/docker-ubuntu1804-ansible:latest
    - MOLECULE_DISTRO: geerlingguy/docker-ubuntu1604-ansible:latest
    - MOLECULE_DISTRO: geerlingguy/docker-debian10-ansible:latest
    - MOLECULE_DISTRO: geerlingguy/docker-debian9-ansible:latest
    - MOLECULE_DISTRO: evantill/docker-oraclelinux7-ansible:latest

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME geerlingguy.$ROLE_NAME
  - cd geerlingguy.$ROLE_NAME

script:
  # Run tests.
  - molecule test

branches:
  only:
    - feature-testing

#notifications:
  #webhooks: https://galaxy.ansible.com/api/v1/notifications/
